-- Rode este script no SQL Editor do Supabase para criar as tabelas

-- Tabela de Filmes
CREATE TABLE public.films (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    image TEXT NOT NULL,
    url TEXT NOT NULL,
    summary TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tabela de Séries
CREATE TABLE public.series (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    image TEXT NOT NULL,
    url TEXT NOT NULL,
    summary TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tabela de Categorias
CREATE TABLE public.categories (
    id TEXT PRIMARY KEY, -- ex: 'films', 'series', 'anime'
    name TEXT NOT NULL,
    icon TEXT NOT NULL,
    storage_key TEXT, -- mantido para compatibilidade, mas opcional
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tabela de Itens de Categorias (para categorias personalizadas)
CREATE TABLE public.category_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id TEXT REFERENCES public.categories(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    image TEXT NOT NULL,
    url TEXT NOT NULL,
    summary TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar Row Level Security (RLS) é boa prática, 
-- mas para começar simples vamos permitir acesso público (anon key)
ALTER TABLE public.films ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.series ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.category_items ENABLE ROW LEVEL SECURITY;

-- Políticas de acesso (CRUD completo para anon - cuidado em produção real)
CREATE POLICY "Enable read access for all users" ON public.films FOR SELECT USING (true);
CREATE POLICY "Enable insert for all users" ON public.films FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for all users" ON public.films FOR UPDATE USING (true);
CREATE POLICY "Enable delete for all users" ON public.films FOR DELETE USING (true);

CREATE POLICY "Enable read access for all users" ON public.series FOR SELECT USING (true);
CREATE POLICY "Enable insert for all users" ON public.series FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for all users" ON public.series FOR UPDATE USING (true);
CREATE POLICY "Enable delete for all users" ON public.series FOR DELETE USING (true);

CREATE POLICY "Enable read access for all users" ON public.categories FOR SELECT USING (true);
CREATE POLICY "Enable insert for all users" ON public.categories FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for all users" ON public.categories FOR UPDATE USING (true);
CREATE POLICY "Enable delete for all users" ON public.categories FOR DELETE USING (true);

CREATE POLICY "Enable read access for all users" ON public.category_items FOR SELECT USING (true);
CREATE POLICY "Enable insert for all users" ON public.category_items FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for all users" ON public.category_items FOR UPDATE USING (true);
CREATE POLICY "Enable delete for all users" ON public.category_items FOR DELETE USING (true);
